# Generated by Django 2.1.15 on 2020-06-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='Page',
        ),
    ]
